[versions]
agp = "8.6.1"
kotlin = "2.1.10"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
safeArgs = "2.8.8"
serialization = "2.1.10"
navVersion = "2.8.8"
kotlinxSerializationJson = "1.8.0"
glide = "4.16.0"
ksp = "2.1.10-1.0.29"
roomRuntime = "2.6.1"
okhttp = "4.12.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
lottie = "6.4.1"
datastore = "1.1.3"
pagingRuntimeKtx = "3.3.6"
daggerHilt = "2.55"
googleGmsGoogleServices = "4.4.2"
firebaseAuth = "23.2.0"
shimmer = "0.5.0"
splashScreen = "1.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
safeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "safeArgs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

#navigation
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navVersion" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navVersion" }

#glide
glide = {group = "com.github.bumptech.glide",name = "glide",version.ref = "glide"}

#lotte
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

#retrofit
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }

#room
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

#datastore
preferences-datastore = {group = "androidx.datastore",name ="datastore-preferences",version.ref = "datastore"}

#dagger hilt
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android",version.ref = "daggerHilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler",version.ref = "daggerHilt" }

#pading
androidx-paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }

#splash screen
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
splash-screen = {group="androidx.core",name="core-splashscreen",version.ref = "splashScreen"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
safeArgs = { id = "androidx.navigation.safeargs.kotlin"}
ksp = {id = "com.google.devtools.ksp",version.ref = "ksp"}
dagger-hilt = {id = "com.google.dagger.hilt.android",version.ref = "daggerHilt"}
room-plugin = {id = "androidx.room" , version.ref = "roomRuntime"}
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
